sudo apt-get -y update;
sudo apt-get -y install python3;
sudo apt-get -y install python3-pip;
sudo apt-get -y install python3-dev;
sudo apt-get -y install git;
sudo pip3 install setuptools;
sudo pip3 install discord==0.16.12;
sudo pip3 install asyncio;
sudo pip3 install requests;
sudo pip3 install flask;
sudo git clone https://github.com/Luke7864/control_bot;